# Generated by Django 4.2.5 on 2023-09-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tarefa_finalizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='finalizada',
        ),
    ]
