# Generated by Django 4.2.5 on 2023-09-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tarefa_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
