# Generated by Django 4.2.5 on 2023-09-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tarefa_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
