# Generated by Django 4.2.5 on 2023-09-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tarefa_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
